### ISSUE TITLE
README appears to be missing

### ISSUE THREAD

**Issue by mikeysan** [HarshKapadia2/git_basics_hosting_test#1]
I am guessing, given how detailed your readme.md file is on git_basics, you are already putting one together for this repo.

I am raising this issue because it is better to ask than assume.

**Comment by HarshKapadia2** [comment]
Hey!
I am using this repo to experiment hosting on GitHub Pages. I have made a better version of git_basics using Asciidoctor and was working out things.
I'll be making the final changes on git_basics and will delete this repo...

**Comment by HarshKapadia2** [comment]
Thank you so much for your concern and for checking out git_basics! Hope it helped you!
